version: '3'

services:
  basic:
    build: ./01-basic
    # volumes:
    #   - .:/app
    ports:
      - "5001:5000"
    environment:
      - PYTHONUNBUFFERED=1

  connexion:
    build: ./02-connexion
    ports:
      - "5002:5000"
      - "5003:8080"
